"use client"

import { useEffect, useState } from "react"
import { ArrowLeft, ArrowRight, Check, ChevronDown, Copy, ImagePlus, Mail, Play, RotateCcw, Settings2, Sparkles, Trash2, Upload, Video, X } from "lucide-react"

type Memory = { id: string; type: "image" | "video"; src: string; name: string }
type Settings = { autoScroll: boolean; speed: number; duration: number; darkness: number; zoom: number; layout: "center" | "left" | "right" }
type Letter = { id: string; title: string; date: string; recipientName: string; recipientEmail: string; senderName: string; content: string; memories: Memory[]; settings: Settings }
const defaults: Settings = { autoScroll: true, speed: 18, duration: 7, darkness: 65, zoom: 20, layout: "center" }
const exampleMemories: Memory[] = [{ id: "one", type: "image", src: "/memory-1.png", name: "Meadow at golden hour" }, { id: "two", type: "image", src: "/memory-2.png", name: "A quiet morning" }, { id: "three", type: "image", src: "/memory-3.png", name: "The long way home" }]
const initial: Letter = { id: "", title: "", date: new Date().toISOString().slice(0, 10), recipientName: "", recipientEmail: "phamnguyen1700@gmail.com", senderName: "", content: "", memories: [], settings: defaults }

function Logo() { return <div className="lk-logo"><span className="lk-logo-mark"><Sparkles size={14} /></span><span>Love Keeper</span></div> }
function Stepper({ step }: { step: number }) { return <div className="lk-stepper" aria-label="Letter creation steps">{["Write", "Memories", "Review", "Share"].map((label, i) => <div className={i === step ? "lk-step active" : i < step ? "lk-step done" : "lk-step"} key={label}><span>{i < step ? <Check size={13} /> : i + 1}</span>{label}</div>)}</div> }
function Header({ step }: { step: number }) { return <header className="lk-topbar"><Logo /><Stepper step={step} /><span className="lk-demo-pill">Frontend demo</span></header> }
function SettingsPanel({ settings, onChange, onClose }: { settings: Settings; onChange: (s: Settings) => void; onClose: () => void }) { const update = (key: keyof Settings, value: string | number | boolean) => onChange({ ...settings, [key]: value }); return <div className="lk-settings-backdrop" onClick={onClose}><section className="lk-settings" onClick={e => e.stopPropagation()}><div className="lk-settings-head"><div><p className="lk-eyebrow">Playback</p><h2>Shape the atmosphere</h2></div><button className="lk-icon" onClick={onClose} aria-label="Close settings"><X size={18} /></button></div><label className="lk-switch-row">Letter auto-scroll <input type="checkbox" checked={settings.autoScroll} onChange={e => update("autoScroll", e.target.checked)} /><span className="lk-switch" /></label>{([["speed", "Letter speed", "px / sec", 5, 40], ["duration", "Image duration", "seconds", 3, 15], ["darkness", "Background darkness", "%", 30, 90], ["zoom", "Image zoom", "%", 0, 50]] as const).map(([key, label, suffix, min, max]) => <label className="lk-range" key={key}><span>{label}<b>{settings[key]} {suffix}</b></span><input type="range" min={min} max={max} value={settings[key]} onChange={e => update(key, Number(e.target.value))} /></label>)}<div className="lk-range"><span>Letter position</span><div className="lk-segments">{(["left", "center", "right"] as const).map(value => <button key={value} className={settings.layout === value ? "selected" : ""} onClick={() => update("layout", value)}>{value}</button>)}</div></div><button className="lk-text-button" onClick={() => onChange(defaults)}><RotateCcw size={14} /> Reset defaults</button><button className="lk-button primary full" onClick={onClose}>Done</button></section></div> }
function MemoryStage({ letter, autoPlay = false }: { letter: Letter; autoPlay?: boolean }) { const [active, setActive] = useState(0); const [settingsOpen, setSettingsOpen] = useState(false); const [playing, setPlaying] = useState(autoPlay); const memories = letter.memories.length ? letter.memories : exampleMemories; useEffect(() => { if (!playing || memories.length < 2) return; const timer = window.setInterval(() => setActive(v => (v + 1) % memories.length), letter.settings.duration * 1000); return () => window.clearInterval(timer) }, [playing, memories.length, letter.settings.duration]); return <div className="lk-memory-stage" style={{ ["--darkness" as string]: `${letter.settings.darkness / 100}`, ["--zoom" as string]: `${1 + letter.settings.zoom / 100}` }}>{memories.map((memory, i) => <img key={memory.id} className={`lk-memory ${active === i ? "visible" : ""}`} src={memory.src} alt={memory.name} />)}<div className={`lk-memory-shade ${letter.settings.layout}`} /><div className={`lk-letter-reading ${letter.settings.layout}`}><div className="lk-reading-meta">{letter.date} <span /> To {letter.recipientName || "someone dear"}</div><div className="lk-reading-body">{letter.content || "The days we keep are made of little things. A shared look, a familiar street, the way light found us when we least expected it."}</div><p className="lk-reading-signature">{letter.senderName || "With love"}</p></div><div className="lk-reader-controls"><button className="lk-icon" onClick={() => setPlaying(v => !v)} aria-label={playing ? "Pause memories" : "Play memories"}>{playing ? <span className="pause-bars">Ⅱ</span> : <Play size={16} fill="currentColor" />}</button><span>{active + 1} / {memories.length}</span><button className="lk-icon" onClick={() => setSettingsOpen(true)} aria-label="Playback settings"><Settings2 size={16} /></button></div>{settingsOpen && <SettingsPanel settings={letter.settings} onChange={() => {}} onClose={() => setSettingsOpen(false)} />}</div> }
function WriteStep({ letter, setLetter, next }: { letter: Letter; setLetter: (l: Letter) => void; next: () => void }) { const [error, setError] = useState(""); const update = (key: keyof Letter, value: string) => setLetter({ ...letter, [key]: value }); return <div className="lk-editor-grid"><section><p className="lk-eyebrow">A letter, kept close</p><h1>Say what you mean.</h1><p className="lk-lede">There are some things that deserve a little more time, and a place to return to.</p><div className="lk-form"><label>Date<input type="date" value={letter.date} onChange={e => update("date", e.target.value)} /></label><label>To<input placeholder="Their name" value={letter.recipientName} onChange={e => update("recipientName", e.target.value)} /></label><label className="wide">Your letter<textarea className="lk-stationery" placeholder="Dear you,\n\nStart writing here..." value={letter.content} onChange={e => update("content", e.target.value)} /></label><label>Sign your name<input placeholder="With love, ..." value={letter.senderName} onChange={e => update("senderName", e.target.value)} /></label></div>{error && <p className="lk-error">{error}</p>}<button className="lk-button primary" onClick={() => { if (!letter.recipientName || !letter.content || !letter.senderName) { setError("Please add a recipient, your words, and a signature."); return } next() }}>Continue <ArrowRight size={16} /></button></section><aside className="lk-editor-note"><span className="lk-note-pin" /><p>“Some memories deserve more than a message.”</p><small>— Love Keeper</small></aside></div> }
function MemoriesStep({ letter, setLetter, next, back }: { letter: Letter; setLetter: (l: Letter) => void; next: () => void; back: () => void }) { const add = (files: FileList | null) => { if (!files) return; const items = Array.from(files).filter(f => f.type.startsWith("image/") || f.type.startsWith("video/")).map(file => ({ id: crypto.randomUUID(), type: file.type.startsWith("video/") ? "video" as const : "image" as const, src: URL.createObjectURL(file), name: file.name })); setLetter({ ...letter, memories: [...letter.memories, ...items] }) }; const remove = (id: string) => setLetter({ ...letter, memories: letter.memories.filter(m => m.id !== id) }); return <div className="lk-narrow"><div className="lk-section-heading"><div><p className="lk-eyebrow">Chapter two</p><h1>Keep the moments.</h1><p className="lk-lede">Add a few pieces of the story. If you skip this, we&apos;ll set a scene for you.</p></div><span className="lk-premium">Video · demo</span></div><label className="lk-dropzone"><Upload size={22} /><strong>Drop memories here</strong><span>or browse photos and videos</span><input type="file" accept="image/*,video/*" multiple onChange={e => add(e.target.files)} /></label><div className="lk-memory-grid">{(letter.memories.length ? letter.memories : exampleMemories).map(memory => <div className="lk-memory-card" key={memory.id}><img src={memory.src} alt={memory.name} /><button onClick={() => letter.memories.length && remove(memory.id)} aria-label={`Remove ${memory.name}`}><Trash2 size={14} /></button><span>{memory.type === "video" ? <Video size={12} /> : <ImagePlus size={12} />}{memory.name}</span></div>)}</div><div className="lk-actions"><button className="lk-button secondary" onClick={back}><ArrowLeft size={16} /> Back</button><button className="lk-button primary" onClick={next}>Preview letter <ArrowRight size={16} /></button></div></div> }
function Delivery({ letter, setLetter, back }: { letter: Letter; setLetter: (l: Letter) => void; back: () => void }) { const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const send = () => { if (!letter.title) return; setBusy(true); const complete = { ...letter, id: crypto.randomUUID() }; window.setTimeout(() => { localStorage.setItem(`love-keeper-${complete.id}`, JSON.stringify(complete)); setLetter(complete); setBusy(false); setSent(true) }, 750) }; if (sent) return <div className="lk-success"><div className="lk-success-icon"><Check size={28} /></div><p className="lk-eyebrow">Demo delivery complete</p><h1>Your letter is ready.</h1><p>Nothing was emailed — this is a local prototype. The demo link below opens the reading experience in this browser.</p><div className="lk-linkbox">{location.origin}/letters/{letter.id}<button onClick={() => navigator.clipboard?.writeText(`${location.origin}/letters/${letter.id}`)}><Copy size={15} /></button></div><div className="lk-actions center"><button className="lk-button primary" onClick={() => location.href = `/letters/${letter.id}`}>Read letter <Play size={15} fill="currentColor" /></button></div></div>; return <div className="lk-narrow delivery"><p className="lk-eyebrow">One last detail</p><h1>Send it gently.</h1><p className="lk-lede">Give this memory a name, then share its private demo link.</p><label>Letter title<input placeholder="A little note for you" value={letter.title} onChange={e => setLetter({ ...letter, title: e.target.value })} /></label><label>Recipient email<input type="email" value={letter.recipientEmail} onChange={e => setLetter({ ...letter, recipientEmail: e.target.value })} /></label><p className="lk-demo-copy"><Mail size={15} /> Sending is simulated. No actual email will be sent.</p><div className="lk-actions"><button className="lk-button secondary" onClick={back}><ArrowLeft size={16} /> Back</button><button className="lk-button primary" disabled={!letter.title || busy} onClick={send}>{busy ? "Preparing..." : <>Send demo letter <Mail size={15} /></>}</button></div></div> }
export default function HomePage() { const [step, setStep] = useState(0); const [letter, setLetter] = useState<Letter>(initial); const next = () => setStep(v => Math.min(v + 1, 3)); const back = () => setStep(v => Math.max(v - 1, 0)); return <main className="lk-app"><Header step={step} />{step === 0 && <WriteStep letter={letter} setLetter={setLetter} next={next} />}{step === 1 && <MemoriesStep letter={letter} setLetter={setLetter} next={next} back={back} />}{step === 2 && <div className="lk-review"><div className="lk-review-top"><div><p className="lk-eyebrow">The finished feeling</p><h1>Read it as they will.</h1></div><button className="lk-button secondary" onClick={() => setStep(0)}><ChevronDown size={15} /> Edit letter</button></div><MemoryStage letter={letter} autoPlay /><div className="lk-review-bottom"><button className="lk-button secondary" onClick={back}><ArrowLeft size={16} /> Back</button><button className="lk-button primary" onClick={next}>Continue to share <ArrowRight size={16} /></button></div></div>}{step === 3 && <Delivery letter={letter} setLetter={setLetter} back={back} />}</main> }
export { MemoryStage, defaults, exampleMemories }

// End of the frontend-only prototype.
       
